spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HotelManagementSystem
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: hotelgrand.sinharaja@gmail.com
    password: aunw oytm qrct rqsu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true